### PR TITLE
Fix/class refactor util

### LINKED ISSUE #36: Refactor User.js
- [ ]  clean methods
- [ ] method consolidation
- [ ]  use arrow functions
- [ ]  run tests after each change. atomic commits could help

### LINKED ISSUE #38: Refactor Sleep.js
- [ ]  clean methods
- [ ] method consolidation
- [ ]  use arrow functions
- [ ]  run tests after each change. atomic commits could help

### LINKED ISSUE #39: Refactor Hydration.js
- [ ]  clean methods
- [ ] method consolidation
- [ ]  use arrow functions
- [ ]  run tests after each change. atomic commits could help

### LINKED ISSUE #40: Add util.js file to hold commonly shared functionality between the different classes.
look for common usage and method bodies that are near duplicates, re-write them for reusability and then go ahead and add those into a util.js file.

IT MAY BE HELPFUL TO USE A DIFF CHECKER TO SEE COMMONLY SHARED LINES OF CODE.

Checkout diffchecker.com

### PR DESCRIPTION
**Pull request by BigBike96**
[X] - Fix
[X] - Refactor

use functions in util file in class methods to clean up code
remove extra characters

### CODE REVIEW

File: src/Activity.js [hunk 1]
```diff
@@ -29,9 +29,16 @@ class Activity {
...
     return this.activityData.filter(data => id === data.userID).reduce((acc, elem) => (elem.flightsOfStairs > acc) ? elem.flightsOfStairs : acc, 0);
   }
+
+  // breaks tests, but gets rid of some decimals. The values are good
   getAllUserAverageForDay(date, userRepo, relevantData) {
     let selectedDayData = userRepo.chooseDayDataForAllUsers(this.activityData, date);
-    return parseFloat((selectedDayData.reduce((acc, elem) => acc += elem[relevantData], 0) / selectedDayData.length).toFixed(1));
+
+     // const average =
+     return parseFloat(averager(selectedDayData, relevantData).toFixed(1))
```
Comment (shayan-golafshani) [inline src/Activity.js:38]: Nice job sticking parseFloat().

parseInt() might've messed somethings up.

File: src/Hydration.js [hunk 2]
```diff
@@ -10,18 +10,17 @@ class Hydration {
...
   }
 
   calculateFirstWeekOunces(userRepo, id) {
     return userRepo.getFirstWeek(id, this.hydrationData).map((data) => `${data.date}: ${data.numOunces}`);
   }
-  
+
   calculateRandomWeekOunces(date, id, userRepo) {
-    return findDataByDate(this.hydrationData, date, id, userRepo, 'numOunces');
+    return findDataByDate(date, id, this.hydrationData, userRepo, 'numOunces');
```
Comment (shayan-golafshani) [inline src/Hydration.js:22]: Nice job refactoring  the order

File: src/User-repo.js [hunk 3]
```diff
@@ -60,23 +60,17 @@ class UserRepo {
...
     let sortedObjectKeys = this.isolateUsernameAndRelevantData(dataSet, date, relevantData, listFromMethod)
     return Object.keys(sortedObjectKeys).sort((b, a) => {
-      return (sortedObjectKeys[a].reduce((sumSoFar, sleepQualityValue) => {
-        sumSoFar += sleepQualityValue
-        return sumSoFar;
-      }, 0) / sortedObjectKeys[a].length) - (sortedObjectKeys[b].reduce((sumSoFar, sleepQualityValue) => {
-        sumSoFar += sleepQualityValue
-        return sumSoFar;
-      }, 0) / sortedObjectKeys[b].length)
+        return averager(sortedObjectKeys[a]) - averager(sortedObjectKeys[b])
```
Comment (shayan-golafshani) [inline src/User-repo.js:63]: Nice job cutting out duplicate code mate!

File: src/util.js [hunk 4]
```diff
@@ -1,11 +1,19 @@
-export const averager = (array, key) => array.reduce((acc, data) => acc += data[key], 0) / array.length;
+
+export const averager = (array, key) => {
+  if (key !== undefined) {
```
Comment (shayan-golafshani) [inline src/util.js:3]: Great job making this function dynamic and usable in multiple situations

**Review by shayan-golafshani — APPROVED** [review]
Nice job!
