### PR TITLE
Fix/class refactor util

### LINKED ISSUE #34: [javaScript] User-repo.js
### [javaScript] User-repo.js
I am in shambles, I don't even know where to begin. We'll need to cross reference the fitlit rubric and try and figure out exactly what this repo is doing. This ticket is **dynamic,** please update this as we figure more out.
- [ ] Figure out exactly what the User-Repo should be doing
- [ ] What is it not doing?
- [ ] Mark which functions could be combined
- [ ] Mark which functions dont belong there
- [ ] Figure out where the unneeded function need to go.
- [ ] Remove all ES5 and convert to ES6 basics (var, const, let, function)
- [ ] The names are... long. Can they be more concise?
- [ ] Redundant variables that could be a property
- [ ] Wait, are we missing a lot properties to store data? what properties should our class have.
- [ ] Method names could have better naming.

### LINKED ISSUE #35: Refactor Activity.js
- [ ]  clean methods
- [ ] method consolidation
- [ ]  use arrow functions
- [ ]  run tests after each change. atomic commits could help

### LINKED ISSUE #37: Refactor User-repo.js
- [ ]  clean methods
- [ ] method consolidation
- [ ]  use arrow functions
- [ ]  run tests after each change. atomic commits could help

### PR DESCRIPTION
**Pull request by BigBike96**
[X] - fix

this should be the final refactor of all of the classes
functions in util file

### CODE REVIEW

File: src/Activity.js [hunk 1]
```diff
@@ -1,69 +1,62 @@
...
   }
+
   accomplishStepGoal(id, date, userRepo) {
-    let userStepsByDate = this.activityData.find(data => id === data.userID && date === data.date);
-    if (userStepsByDate.numSteps === userRepo.dailyStepGoal) {
-      return true;
-    }
-    return false
+    let userStepsByDate = finder(this.activityData, id, date);
+    return userStepsByDate.numSteps === userRepo.dailyStepGoal ? true : false;
```
Comment (ghost) [inline src/Activity.js:25]: Nice simplification!

File: src/Activity.js [hunk 2]
```diff
@@ -1,69 +1,62 @@
...
   getFriendsActivity(user, userRepo) {
     let data = this.activityData;
-    let userDatalist = user.friends.map((friend) => {
-      return userRepo.getDataFromUserID(friend, data)
-    });
-    return userDatalist.reduce((arraySoFar, listItem) => {
-      return arraySoFar.concat(listItem);
-    }, []);
+    let userDatalist = user.friends.map(friend => userRepo.getDataFromUserID(friend, data));
+    return userDatalist.reduce((arraySoFar, listItem) => arraySoFar.concat(listItem), []);
```
Comment (ghost) [inline src/Activity.js:53]: Also very nice simplifying here!

File: src/Activity.js [hunk 3]
```diff
@@ -72,16 +65,15 @@ class Activity {
...
 
   showcaseWinner(user, date, userRepo) {
-    let namedList = this.showChallengeListAndWinner(user, date, userRepo);
-    let winner = this.showChallengeListAndWinner(user, date, userRepo).shift();
-
-    console.log('winner>>>>>>>>>>', winner);
-    return winner;
+    // NAMED LIST IS NOT BEING USED AT THIS TIME 6-6 @ 6:30PM
+    // let namedList = this.showChallengeListAndWinner(user, date, userRepo);
+    // console.log('namedList>>>>>>>>>>', namedList);
```
Comment (ghost) [inline src/Activity.js:75]: Thank you for removing comments

**Review by ghost — APPROVED** [review]
Looks great, glad to have this done!
